---
services:
  url_service_db:
    container_name: url_service_db
    image: postgres:12
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  url_service:
    container_name: url_service
    build:
      context: ../core
    env_file:
      - .env
    restart: always
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@url_service_db:5432/${POSTGRES_DB}?schema=public
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - url_service_db
